services:
  studio-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GEMINI_API_KEY=${GEMINI_API_KEY}
    container_name: studio-app-prod
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    # Configuración de recursos (opcional)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    # Healthcheck para verificar que la aplicación esté funcionando
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
