version: '3.8'

services:
  studio-app:
    image: node:20-alpine
    container_name: studio-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm install && npm run build && npm start"
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
